[package]
name = "mague-rc"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
url = "2.5.4"
